/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "RUT"
/rat/db/set DETECTOR geo_file "RUT/rut.geo"
/tracking/storeTrajectory 1

/run/initialize
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/open OGLIQt
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

/generator/add combo gun:point
/generator/vtx/set opticalphoton  0 0 0 .0000031
/generator/pos/set 0 0 1000
